// <auto-generated />
using System;
using CryptoFolioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoFolioAPI.Migrations
{
    [DbContext(typeof(CryptoFolioContext))]
    [Migration("20200904185657_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptoFolioAPI.Models.Entities.Coin", b =>
                {
                    b.Property<int>("CoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoinId");

                    b.ToTable("Coin");
                });

            modelBuilder.Entity("CryptoFolioAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoFolioAPI.Models.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("WalletId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("CryptoFolioAPI.Models.Entities.WalletCoin", b =>
                {
                    b.Property<int>("WalletCoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CoinId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValueWhenBought")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("WalletCoinId");

                    b.HasIndex("CoinId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletCoin");
                });

            modelBuilder.Entity("CryptoFolioAPI.Models.Entities.User", b =>
                {
                    b.HasOne("CryptoFolioAPI.Models.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");
                });

            modelBuilder.Entity("CryptoFolioAPI.Models.Entities.WalletCoin", b =>
                {
                    b.HasOne("CryptoFolioAPI.Models.Entities.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId");

                    b.HasOne("CryptoFolioAPI.Models.Entities.Wallet", null)
                        .WithMany("Walletcoins")
                        .HasForeignKey("WalletId");
                });
#pragma warning restore 612, 618
        }
    }
}
